# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: noFAYZ.Zuno
PackageVersion: 1.1.2
InstallerType: nullsoft
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/noFAYZ/zuno/releases/download/v1.1.2/Zuno_1.1.2_x64-setup.exe
  InstallerSha256: 62424AE146E90E1174BDF2BD78C4EFACE9AC4C8C3297DE70FFCC3F1BD8D3BD92
ManifestType: installer
ManifestVersion: 1.12.0
