# Created using wingetcreate 1.12.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: noFAYZ.Zuno
PackageVersion: 1.1.2
PackageLocale: en-US
Publisher: noFFAYZ
PackageName: Zuno
License: Apache
ShortDescription: A Youtube Music Desktop client
ManifestType: defaultLocale
ManifestVersion: 1.12.0
